dist: trusty
sudo: false
language: python
env: 
    global:
        - DJANGO_SETTINGS_MODULE='project.settings.settings_dev'    

python:
    - "2.7"

install:
    - pip install -r requirements.txt


